- name: variables from play level
  hosts: localhost
  vars:
   course: "devops"
   trainer: "shivakumar"
   duration: "110 hours"
  tasks:
   - name: check variables
     vars:
      course: "devops with aws"
  ansible.builtin.debug:
   msg: "hello, i am learning {{course}} , trainer is {{trainer}} , duration is {{duration}}"