- name: loops
  hosts: localhost
  become: yes
  tasks: 
  - name: install and uninstall packages
    ansible.builtin.package:
     name: "{{item.name}}"
     state: "{{item.status}}"
    loop:
    - {name: 'git' , state:'absent'}
    - {name: 'mysql' , state:'present'}
    - {name: 'postfix' , state:'absent'}
    - {name: 'nginx' , state:'present'}
